### ISSUE TITLE
td-agent won't start due to the plugin

### ISSUE THREAD

**Issue by asafm** [y-ken/fluent-plugin-watch-process#2] opened 2016-02-29 09:22 UTC
```
opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate fluent-mixin-type-converter-0.0.3, because fluentd-0.12.20 conflicts with fluentd (~> 0.10.42) (Gem::ConflictError)
    from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1280:in `activate'
    from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
    from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
    from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
    from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-watch-process-0.0.3/lib/fluent/plugin/in_watch_process.rb:2:in `<top (required)>'
    from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin.rb:168:in `block in try_load_plugin'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin.rb:166:in `each'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin.rb:166:in `try_load_plugin'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin.rb:126:in `new_impl'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin.rb:53:in `new_input'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/root_agent.rb:145:in `add_source'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/root_agent.rb:91:in `block in configure'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/root_agent.rb:88:in `each'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/root_agent.rb:88:in `configure'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/engine.rb:117:in `configure'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/engine.rb:91:in `run_configure'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:515:in `run_configure'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:146:in `block in start'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:352:in `call'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:352:in `main_process'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:325:in `block in supervise'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:324:in `fork'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:324:in `supervise'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:142:in `start'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/command/fluentd.rb:171:in `<top (required)>'
    from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/bin/fluentd:6:in `<top (required)>'
    from /opt/td-agent/embedded/bin/fluentd:23:in `load'
    from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
    from /usr/sbin/td-agent:7:in `load'
    from /usr/sbin/td-agent:7:in `<main>'

```

**Comment by asafm** [comment] 2016-02-29 09:24
I install [td-agent](http://docs.fluentd.org/articles/install-by-deb) on Ubuntu Trusty, installed the graphite plugin and then yours, try restarting td-agent and this is what I got

**Comment by y-ken** [comment] 2016-02-29 10:25
Hi @asafm 
I'll release fixed version soon.

**Comment by y-ken** [comment] 2016-02-29 10:47
I have updated the dependent plugin version.
Please update with following instruction.

```bash
td-agent-gem install fluent-mixin-type-converter
```

**Comment by asafm** [comment] 2016-03-02 10:05
Awesome! td-agent started! Thanks for the quick response

**Comment by danielserrao** [comment] 2017-12-12 13:46
I have what it seems exactly the same problem when I try to execute "/etc/init.d/td-agent restart" . Installed the fluent-mixin-type-converter, but it still continues. The problem only happens when I add a ruby file in the /etc/td-agent/plugin, if I remove the file I can restart the td-agent again successfully. Any idea of what could be happening? Maybe I will open a new issue with the exact error log.

**Comment by y-ken** [comment] 2017-12-12 14:03
Would you please follow up this problem? @okkez
It may happen by the mixin plugins which I guess.
* https://github.com/y-ken/fluent-mixin-type-converter
* https://github.com/y-ken/fluent-mixin-rewrite-tag-name

**Comment by okkez** [comment] 2017-12-12 15:15
OK, I will check later.

**Comment by okkez** [comment] 2017-12-13 03:21
I've checked this issue but I could not reproduce the situation.

@danielserrao Could show me exact error log?

BTW, maybe you can resolve the problem with `--gemfile` option, see https://docs.fluentd.org/v0.12/articles/plugin-management#%E2%80%9C%E2%80%93gemfile%E2%80%9D-option for more details.

**Comment by danielserrao** [comment] 2017-12-13 18:58
Hi @okkez. I'm sorry, but the problem wasn't the td-agent, I'm still learning fluentd :( . Later I understood that the td-agent checks all the requires of the plugin and return an error with a lot of "<top (required)>". I installed the missing packages and the problem was solved.

Thanks for the fast response.

**Comment by y-ken** [comment] 2017-12-17 09:07
I think it need to stop using Fluent::SetTagKeyMixin, Fluent::HandleTagNameMixin and Fluent::Mixin::RewriteTagName
Because v0.14 API does not support these mixins.

**Comment by okkez** [comment] 2017-12-18 00:27
An alternative way for Fluentd v0.14 or later, for example:

* in_exec
  * To run ps command
* filter_grep
  * To exclude header line
* filter_parser + fluent-plugin-grok-parser (or parser_regexp)
  * To parse data and convert value type
* fluent-plugin-rewrite-tag-filter (if needed)
* and some output plugins

**Comment by cosmo0920** [comment] 2021-05-28 05:42
This issue is for Fluentd v0.12 and its Fluentd version is already EOL.
If you hit similar issue on Fluentd v1, please file a new issue in this repository.
Closing.

**Closed by cosmo0920** 2021-05-28 05:42 UTC
